# After a build completes, this workflow analyzes the artifacts and reports back in a comment

name: Analyze

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  check-size:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 20
    steps:
      # report status back to pull request
      - uses: haya14busa/action-workflow_run-status@v1
      - uses: hmarr/debug-action@v1.0.0
      - uses: actions/checkout@v2
      - name: Use Node.js 10 x64
        uses: actions/setup-node@v2-beta
        with:
          node-version: 10
          architecture: x64
      - run: yarn install --frozen-lockfile
      - name: Download branch artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: dist
          path: after
          repo: maplibre/maplibre-gl-js
      - name: Download base artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          workflow: build.yml
          commit: ${{ github.event.workflow_run.pull_requests[0].base.sha }}
          name: dist
          path: before
          repo: maplibre/maplibre-gl-js
      - run: yarn source-map-explorer before/mapbox-gl.js --gzip --json before.json
      - run: yarn source-map-explorer after/mapbox-gl.js --gzip --json after.json
      - name: Build bundle size report
        run: node build/check-bundle-size.js > comment-body.txt
      - name: Dump bundle size report
        run: cat comment-body.txt

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: comment-body.txt
          header: bundle-size-report
          number: ${{ github.event.workflow_run.pull_requests[0].number }}
