name: CI Test Render

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test_render:
    name: Test Render
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2
        with:
          node-version: 14
          architecture: x64
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build-dev

      - name: Test
        run: |
          npm run test-unit
          npm run test-render
          npm run test-query
          npm run test-expressions
