# This workflow will install node dependencies, build the source code and run the tests

name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint_build_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        node_version:
          - 14
        architecture:
          - x64

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: npm ci

      - run: npm run lint
      - run: npm run build-dev
      - run: npm run test-unit

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          architecture: x64
      - run: npm ci
      - run: npm run lint
      - run: npm run lint-docs
      - run: npm run lint-css

  test-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          architecture: x64
      - run: npm ci
      - run: npm run build-dev
      # see: https://github.com/stackgl/headless-gl#how-can-headless-gl-be-used-on-a-headless-linux-machine
      - run: xvfb-run -s "-ac -screen 0 1280x1024x24" npm run test-unit

  test-query:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          architecture: x64
      - run: npm ci
      - run: npm run build-dev
      - run: npm run test-query
      - uses: actions/upload-artifact@v2
        with:
          path: ./test/integration/query-tests
          name: querytests
      - uses: actions/upload-artifact@v2
        with:
          path: ./test/integration/query-tests/index.html
          name: querytests.html

  test-expressions:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          architecture: x64
      - run: npm ci
      - run: npm run build-dev
      - run: npm run test-expressions

  test-browser:
    timeout-minutes: 20
    # These are a bit flaky and occasionally time out
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          architecture: x64
      - run: npm ci
      - run: npm run build-dev
      - run: DETECT_CHROMEDRIVER_VERSION=true npm install -g chromedriver
      - run: npm install -g geckodriver@2.0.4
      - name: Test Chrome
        env:
          SELENIUM_BROWSER: chrome
          TAP_COLORS: 1
        run: xvfb-run -s "-ac -screen 0 1280x1024x24" npm run test-browser
      - name: Test Firefox
        env:
          SELENIUM_BROWSER: firefox
          TAP_COLORS: 1
        run: xvfb-run -s "-ac -screen 0 1280x1024x24" npm run test-browser

  test-render:
    name: Run render tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2
        with:
          node-version: 14
          architecture: x64
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Test
        run: |
          npm run build-tsc
          npm run test-render
