name: Integration Test - Browser

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test_browser:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Install fonts-noto-cjk
        run: |
          sudo apt-get update
          sudo apt-get install fonts-noto-cjk
      - name: Use Node.js 16 x64
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
          architecture: x64
      - run: npm ci
      - run: npm run build-dev
      - run: xvfb-run -s "-ac -screen 0 1280x1024x24" npm run test-browser