name: Integration Test - Expression

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test_expression:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16 x64
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
          architecture: x64
      - run: npm ci
      - run: npm run test-expression
