name: Upload Benchmarks

on:
  push:
    branches:
      - 1.x
    tags:
      - v1*

jobs:
  upload_benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10 x64
        uses: actions/setup-node@v2
        with:
          node-version: 10
          architecture: x64

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build benchmarks
        run: yarn run build-benchmarks

      - name: Copy benchmarks_generated.js
        run: |
          mkdir tmp
          cp bench/versions/benchmarks_generated.js tmp
          cp bench/versions/benchmarks_generated.js.map tmp

      - name: Upload to GitHub Pages (main)
        if: startsWith(github.ref, 'refs/heads/1.x')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tmp
          destination_dir: benchmarks/1.x

      - name: Get tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload to GitHub Pages (tag)
        if: startsWith(github.ref, 'refs/tags/v1')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tmp
          destination_dir: benchmarks/${{ env.TAG }}
