name: Upload Benchmarks

on:
  push:
    branches:
      - main

jobs:
  upload_benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Use Node.js from nvmrc
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v4
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci

      - name: Build benchmarks
        run: |
          npm run generate-typings
          npm run build-benchmarks

      - name: Copy benchmarks_generated.js
        run: |
          mkdir tmp
          cp test/bench/versions/benchmarks_generated.js tmp
          cp test/bench/versions/benchmarks_generated.js.map tmp

      - name: Upload to GitHub Pages (main)
        if: startsWith(github.ref, 'refs/heads/main')
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: tmp
          destination_dir: benchmarks/main
